# Generated by Django 4.2.15 on 2024-08-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userimage', models.FileField(upload_to='images')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
    ]
