# Generated by Django 3.2.19 on 2024-08-29 05:17

import dish_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=dish_app.models.dish_image_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.categorymodel')),
            ],
        ),
    ]
