# Generated by Django 3.2.19 on 2024-08-28 08:43

import author_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=author_app.models.author_image_path),
        ),
    ]
